-- MySQL Script generated by MySQL Workbench
-- Sun Jan 10 13:12:24 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema m0427
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema m0427
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `m0427` DEFAULT CHARACTER SET utf8 ;
USE `m0427` ;

-- -----------------------------------------------------
-- Table `m0427`.`userInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `m0427`.`userInfo` ;

CREATE TABLE IF NOT EXISTS `m0427`.`userInfo` (
  `userName` VARCHAR(20) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `email` VARCHAR(40) NULL,
  `phone` VARCHAR(45) NULL,
  `nickName` VARCHAR(45) NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `createDateTime` DATETIME NULL,
  `modifyDateTime` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m0427`.`essay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `m0427`.`essay` ;

CREATE TABLE IF NOT EXISTS `m0427`.`essay` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(60) NOT NULL,
  `context` TEXT NULL,
  `createUser` VARCHAR(60) NULL,
  `createDateTime` DATETIME NULL,
  `modifyUser` VARCHAR(60) NULL,
  `modifyDateTime` DATETIME NULL,
  `praise` INT NULL DEFAULT 0,
  `discourage` INT NULL DEFAULT 0,
  `clickNum` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `title`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
